apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::346183682432:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1TH5YFIQDCT07
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn:arn:aws:iam:346183682432:role/UdacityFlaskDeployCBKubectlRole
      username:build
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system

